<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modules\Catalog\FreshFlow.Catalog.Application\FreshFlow.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Catalog\FreshFlow.Catalog.Domain\FreshFlow.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\FreshFlow.API\FreshFlow.API.csproj" />
  </ItemGroup>

</Project>
