namespace FreshFlow.Orders.Application.Abstractions;

public sealed class CreditStatementConcurrencyException : Exception
{
    public CreditStatementConcurrencyException()
        : base("The credit statement was already generated by another request. Please refresh and retry.")
    {
    }

    public CreditStatementConcurrencyException(string message, Exception inner)
        : base(message, inner)
    {
    }
}
