<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="*" />
    <PackageReference Include="MediatR" Version="*" />
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreshFlow.Catalog.Application\FreshFlow.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\FreshFlow.Infrastructure.Persistence\FreshFlow.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
