using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using FreshFlow.Infrastructure.Persistence;
using FreshFlow.Orders.Application.Abstractions;
using FreshFlow.Orders.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace FreshFlow.Orders.Infrastructure.Repositories;

internal sealed class CreditStatementRepository(AppDbContext db) : ICreditStatementRepository
{
    public async Task<CreditStatement?> FindByPeriodAsync(
        Guid restaurantId, DateTime periodStart, CancellationToken ct) =>
        await db.Set<CreditStatement>()
            .Include(s => s.Lines)
            .FirstOrDefaultAsync(s => s.RestaurantId == restaurantId && s.PeriodStart == periodStart, ct);

    public async Task<CreditStatement?> FindByIdAsync(Guid statementId, CancellationToken ct) =>
        await db.Set<CreditStatement>()
            .Include(s => s.Lines)
            .FirstOrDefaultAsync(s => s.Id == statementId, ct);

    public async Task AddAsync(CreditStatement statement, CancellationToken ct) =>
        await db.Set<CreditStatement>().AddAsync(statement, ct);

    public async Task<(IReadOnlyList<CreditStatement> Items, string? NextCursor)> GetPageAsync(
        Guid restaurantId, string? cursor, int pageSize, CancellationToken ct)
    {
        // Guard: pageSize=0 causes Take(0) → empty page, then page[^1] throws
        // IndexOutOfRangeException when building the next cursor.
        if (pageSize <= 0)
            throw new ArgumentException("pageSize must be greater than zero.", nameof(pageSize));

        var query = db.Set<CreditStatement>()
            .AsNoTracking()
            .Where(s => s.RestaurantId == restaurantId);

        // Composite cursor: (PeriodStart DESC, Id DESC) — mirrors CreditRepository's
        // TransactionCursor scheme. PeriodStart is unique per restaurant, so Id only
        // tie-breaks defensively.
        var decoded = StatementCursor.TryDecode(cursor);
        if (decoded is not null)
            query = query.Where(s =>
                s.PeriodStart < decoded.PeriodStart ||
                (s.PeriodStart == decoded.PeriodStart && s.Id < decoded.Id));

        var rows = await query
            .OrderByDescending(s => s.PeriodStart)
            .ThenByDescending(s => s.Id)
            .Take(pageSize + 1)
            .ToListAsync(ct);

        if (rows.Count <= pageSize)
            return (rows.AsReadOnly(), null);

        var page = rows.Take(pageSize).ToList().AsReadOnly();
        var nextCursor = StatementCursor.Encode(page[^1].Id, page[^1].PeriodStart);
        return (page, nextCursor);
    }

    public async Task SaveChangesAsync(CancellationToken ct)
    {
        try
        {
            await db.SaveChangesAsync(ct);
        }
        catch (DbUpdateException ex) when (CreditRepository.IsUniqueViolation(ex))
        {
            throw new CreditStatementConcurrencyException(
                "The credit statement was already generated by another request. Please refresh and retry.", ex);
        }
    }

    // ── Cursor helpers ────────────────────────────────────────────────────────

    /// <summary>
    /// Composite cursor following the same base64-JSON pattern as
    /// <c>CreditRepository.TransactionCursor</c>. Encodes <c>(Id, PeriodStart)</c> of the
    /// last item returned on the previous page.
    /// </summary>
    private sealed record StatementCursor(
        [property: JsonPropertyName("id")] Guid Id,
        [property: JsonPropertyName("periodStart")] DateTime PeriodStart)
    {
        private static readonly JsonSerializerOptions Options = new()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };

        public static StatementCursor? TryDecode(string? encoded)
        {
            if (string.IsNullOrEmpty(encoded)) return null;
            try
            {
                var json = Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
                return JsonSerializer.Deserialize<StatementCursor>(json, Options);
            }
            catch
            {
                return null; // invalid cursor treated as start of list
            }
        }

        public static string Encode(Guid id, DateTime periodStart)
        {
            var json = JsonSerializer.Serialize(new StatementCursor(id, periodStart), Options);
            return Convert.ToBase64String(Encoding.UTF8.GetBytes(json));
        }
    }
}
