<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreshFlow.Catalog.Domain\FreshFlow.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\FreshFlow.SharedKernel\FreshFlow.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\FreshFlow.Contracts\FreshFlow.Contracts.csproj" />
  </ItemGroup>

</Project>
