<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreshFlow.Notifications.Domain\FreshFlow.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\FreshFlow.SharedKernel\FreshFlow.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\FreshFlow.Contracts\FreshFlow.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
